### ISSUE TITLE
Línea del tiempo 
Marlene Maricela Osorio Ramírez 

### ISSUE THREAD

**Issue by MarleneRamirez0731** [SistemasTecTlaxiaco/actividad-7-MarleneRamirez0731#2]
![MARLENE-OSORIO.png](https://user-images.githubusercontent.com/112357070/197621953-b7b36a32-9949-4aa0-ac96-715cc876e3f4.png)

**Comment by AmeliReyesHernandez** [comment]
18.6

**Comment by josealfredo79** [comment]
Hay que utilizar adecuadamente los colores

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
